---
development:
  cloud_name: <%= ENV["CLOUD_NAME"] %>
  api_key: <%= ENV["CLOUDINARY_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_SECRET"] %>
  enhance_image_tag: true
  static_image_support: yes
production:
  cloud_name: <%= ENV["CLOUD_NAME"] %>
  api_key: <%= ENV["CLOUDINARY_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_SECRET"] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: <%= ENV["CLOUD_NAME"] %>
  api_key: <%= ENV["CLOUDINARY_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_SECRET"] %>
  enhance_image_tag: true
  static_image_support: true
